"""Generate the Korean manuscript's claim-ID/status inventory."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MATRIX = ROOT / "research" / "PUBLICATION_CLAIMS.md"
OUTPUT = ROOT / "paper" / "claim-status-ko.tex"
ROW = re.compile(r"^\| ([A-Z]+-\d+) \| ([A-Z]+) \|", re.MULTILINE)


def main() -> int:
    claims = ROW.findall(MATRIX.read_text(encoding="utf-8"))
    if not claims:
        raise SystemExit("publication claim matrix contains no claims")
    lines = [
        "% Generated by scripts/generate_korean_claim_appendix.py.",
        "% Do not edit this inventory by hand.",
        r"\begin{longtable}{L{0.34\linewidth}L{0.56\linewidth}}",
        r"\toprule",
        r"Claim 및 상태 & 권위 있는 근거 위치 \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Claim 및 상태 & 권위 있는 근거 위치 \\",
        r"\midrule",
        r"\endhead",
    ]
    matrix_lines = MATRIX.read_text(encoding="utf-8").splitlines()
    anchors: dict[str, str] = {}
    for line in matrix_lines:
        if not line.startswith("| ") or line.startswith("| ID "):
            continue
        fields = [field.strip() for field in line.strip("|").split("|")]
        if len(fields) == 4 and re.fullmatch(r"[A-Z]+-\d+", fields[0]):
            anchors[fields[0]] = fields[3]
    for claim_id, status in claims:
        anchor = anchors[claim_id].replace("`", "")
        anchor = anchor.replace("_", r"\_")
        lines.append(
            rf"\claimstatus{{{claim_id}}}{{{status}}} & "
            rf"\texttt{{{anchor}}} \\"
        )
    lines.extend((r"\bottomrule", r"\end{longtable}", ""))
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT.relative_to(ROOT)} ({len(claims)} claims)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
